parameters:
    open_orchestra_workflow_function.manager.authorization_workflow_right.class: OpenOrchestra\WorkflowFunction\Manager\AuthorizationWorkflowRightManager

services:
    open_orchestra_workflow_function.manager.authorization_workflow_right:
        class: %open_orchestra_workflow_function.manager.authorization_workflow_right.class%
        arguments:
            - %open_orchestra_workflow_function.document.authorization.class%
